import type { IEventData } from "@/lib/models/event";

export const DEMO_EVENTS: IEventData[] = [
  {
    id: "demo-1",
    title: "Jornada de Acopio de Alimentos",
    organizer: "Red de Voluntarios CABA",
    date: new Date("2026-07-15T10:00:00.000Z"),
    time: "10:00",
    description:
      "Jornada de recolección de alimentos no perecederos para las víctimas del terremoto en Venezuela. Nos reuniremos en la Plaza Central para recibir donaciones de la comunidad. Todo lo recolectado será enviado directamente a las zonas afectadas a través de nuestra red de logística humanitaria.",
    location: "Plaza Central, CABA",
    instagram: "@redvoluntarios",
    googleMaps: "https://maps.google.com/?q=plaza+central+caba",
    phone: "11-1234-5678",
    status: "activo",
  },
  {
    id: "demo-2",
    title: "Taller de Primeros Auxilios",
    organizer: "Brigada de Respuesta Rápida",
    date: new Date("2026-07-15T14:00:00.000Z"),
    time: "14:00",
    description:
      "Capacitación gratuita en primeros auxilios básicos. Aprenderás técnicas de RCP, manejo de heridas y estabilización de emergencias. Este taller es fundamental para quienes viajarán a las zonas afectadas como voluntarios de primera respuesta.",
    location: "Centro Comunitario San Martín, CABA",
    instagram: "@brigada_respuesta",
    googleMaps: "https://maps.google.com/?q=centro+comunitario+san+martin",
    phone: "11-2345-6789",
    status: "activo",
  },
  {
    id: "demo-3",
    title: "Reconstrucción de Viviendas",
    organizer: "Red de Voluntarios CABA",
    date: new Date("2026-07-22T09:00:00.000Z"),
    time: "09:00",
    description:
      "Brigada de construcción y reparación de viviendas damnificadas. Necesitamos voluntarios con experiencia en albañilería, carpintería y electricidad, aunque también recibimos ayuda general para tareas de escombros y limpieza.",
    location: "Barrio 31, CABA",
    instagram: "@redvoluntarios",
    phone: "11-3456-7890",
    status: "pendiente",
  },
  {
    id: "demo-4",
    title: "Campaña de Salud Comunitaria",
    organizer: "Médicos Solidarios",
    date: new Date("2026-07-29T08:00:00.000Z"),
    time: "08:00",
    description:
      "Jornada de atención médica gratuita para la comunidad. Ofreceremos controles generales, vacunación y distribución de medicamentos básicos. Buscamos profesionales de la salud voluntarios y donaciones de insumos médicos.",
    location: "Hospital Municipal, CABA",
    instagram: "@medicos_solidarios",
    googleMaps: "https://maps.google.com/?q=hospital+municipal+caba",
    phone: "11-4567-8901",
    status: "pospuesto",
  },
  {
    id: "demo-5",
    title: "Cena Benéfica Anual",
    organizer: "Fundación Ayuda Ya",
    date: new Date("2026-06-30T20:00:00.000Z"),
    time: "20:00",
    description:
      "Cena de gala con fines benéficos. Todo lo recaudado será destinado a la compra de insumos médicos y alimentos para las víctimas del terremoto. Contaremos con shows en vivo y subasta de obras de arte donadas por artistas locales.",
    location: "Salón de Eventos Palermo, CABA",
    instagram: "@fundacion_ayuda",
    googleMaps: "https://maps.google.com/?q=palermo+caba",
    phone: "11-5678-9012",
    status: "cerrado",
  },
  {
    id: "demo-6",
    title: "Clase de Yoga Solidaria",
    organizer: "Yoga por Venezuela",
    date: new Date("2026-08-02T09:00:00.000Z"),
    time: "09:00",
    description:
      "Clase masiva de yoga al aire libre. La entrada es un alimento no perecedero o un artículo de higiene personal. Todos los niveles son bienvenidos, desde principiantes hasta avanzados.",
    location: "Parque 3 de Febrero, CABA",
    instagram: "@yogaporvenezuela",
    googleMaps: "https://maps.google.com/?q=parque+tres+de+febrero+caba",
    phone: "11-6789-0123",
    status: "activo",
  },
  {
    id: "demo-7",
    title: "Feria de Emprendedores Solidarios",
    organizer: "Mercado Solidario",
    date: new Date("2026-08-08T11:00:00.000Z"),
    time: "11:00",
    description:
      "Feria de emprendedores donde el 50% de las ventas se dona a la causa. Habrá comida artesanal, ropa, accesorios y productos naturales.",
    location: "Plaza Serrano, CABA",
    instagram: "@mercadosolidario",
    phone: "11-7890-1234",
    status: "activo",
  },
  {
    id: "demo-8",
    title: "Charla: Resiliencia en Desastres Naturales",
    organizer: "Universidad de Buenos Aires",
    date: new Date("2026-08-12T18:00:00.000Z"),
    time: "18:00",
    description:
      "Conferencia abierta con expertos en gestión de desastres y resiliencia comunitaria. Abordaremos estrategias de preparación, respuesta y reconstrucción post-terremoto.",
    location: "Facultad de Medicina, UBA",
    instagram: "@uba_solidaria",
    googleMaps: "https://maps.google.com/?q=facultad+medicina+uba",
    status: "pendiente",
  },
  {
    id: "demo-9",
    title: "Maratón por Venezuela",
    organizer: "Corredores Solidarios",
    date: new Date("2026-08-16T07:00:00.000Z"),
    time: "07:00",
    description:
      "Maratón de 10K por las calles de Palermo. Cada corredor aporta una inscripción solidaria que se destina íntegramente a la compra de agua potable y filtros para las comunidades afectadas.",
    location: "Av. Libertador y Figueroa Alcorta, CABA",
    instagram: "@corredoressolidarios",
    phone: "11-8901-2345",
    status: "activo",
  },
  {
    id: "demo-10",
    title: "Taller de Cocina Comunitaria",
    organizer: "Cocineros Sin Fronteras",
    date: new Date("2026-08-22T15:00:00.000Z"),
    time: "15:00",
    description:
      "Aprende a cocinar comidas nutritivas con recursos limitados. Este taller enseña técnicas de cocina comunitaria y conservación de alimentos para situaciones de emergencia.",
    location: "Club de Barrio Almagro, CABA",
    instagram: "@cocinerossinfronteras",
    status: "pendiente",
  },
  {
    id: "demo-11",
    title: "Recital Solidario",
    organizer: "Músicos por Venezuela",
    date: new Date("2026-08-28T19:00:00.000Z"),
    time: "19:00",
    description:
      "Festival musical con bandas locales emergentes y consagradas. Todo el dinero de las entradas se dona a la reconstrucción de escuelas en las zonas afectadas por el terremoto.",
    location: "Teatro Flores, CABA",
    instagram: "@musicosporvenezuela",
    googleMaps: "https://maps.google.com/?q=teatro+flores+caba",
    phone: "11-9012-3456",
    status: "activo",
  },
  {
    id: "demo-12",
    title: "Jornada de Reforestación Urbana",
    organizer: "EcoVoluntarios",
    date: new Date("2026-09-02T08:00:00.000Z"),
    time: "08:00",
    description:
      "Plantación de árboles nativos en espacios públicos de la ciudad. Cada árbol plantado simboliza la esperanza de reconstrucción.",
    location: "Reserva Ecológica Costanera Sur, CABA",
    instagram: "@ecovoluntarios",
    phone: "11-0123-4567",
    status: "pospuesto",
  },
  {
    id: "demo-13",
    title: "Bingo Solidario",
    organizer: "Adultos Mayores Activos",
    date: new Date("2026-09-06T16:00:00.000Z"),
    time: "16:00",
    description:
      "Tarde de bingo con grandes premios donados por comercios locales. El 100% de lo recaudado se destina a la compra de frazadas y abrigo para las familias damnificadas.",
    location: "Sociedad de Fomento Villa Crespo, CABA",
    instagram: "@mayoresactivos",
    googleMaps: "https://maps.google.com/?q=villa+crespo+caba",
    phone: "11-1234-5678",
    status: "pendiente",
  },
  {
    id: "demo-14",
    title: "Curso de Apoyo Psicológico en Crisis",
    organizer: "Psicólogos Solidarios",
    date: new Date("2026-09-12T10:00:00.000Z"),
    time: "10:00",
    description:
      "Formación intensiva en primeros auxilios psicológicos para voluntarios que trabajarán directamente con víctimas del terremoto. Certificación incluida.",
    location: "Sede Colegio de Psicólogos, CABA",
    instagram: "@psicologossolidarios",
    phone: "11-2345-6789",
    status: "activo",
  },
  {
    id: "demo-15",
    title: "Feria del Libro Solidaria",
    organizer: "Bibliotecas Solidarias",
    date: new Date("2026-09-19T14:00:00.000Z"),
    time: "14:00",
    description:
      "Venta de libros donados a precios populares. Recibimos donaciones de libros infantiles para reconstruir bibliotecas escolares destruidas en el terremoto.",
    location: "Biblioteca Nacional, CABA",
    instagram: "@bibliotecassolidarias",
    googleMaps: "https://maps.google.com/?q=biblioteca+nacional+caba",
    phone: "11-3456-7890",
    status: "cerrado",
  },
  {
    id: "demo-16",
    title: "Remate de Arte Solidario",
    organizer: "Artistas por la Reconstrucción",
    date: new Date("2026-09-25T18:00:00.000Z"),
    time: "18:00",
    description:
      "Subasta de obras de arte contemporáneo donadas por artistas argentinos y venezolanos. Los fondos se destinarán a la construcción de viviendas de emergencia.",
    location: "Museo de Arte Moderno, CABA",
    instagram: "@artistasreconstruccion",
    googleMaps: "https://maps.google.com/?q=museo+arte+moderno+caba",
    phone: "11-4567-8901",
    status: "cerrado",
  },
  {
    id: "demo-17",
    title: "Jornada de Donación de Sangre",
    organizer: "Cruz Roja Argentina",
    date: new Date("2026-09-30T08:00:00.000Z"),
    time: "08:00",
    description:
      "Campaña urgente de donación de sangre para los heridos del terremoto. Pueden donar personas de 18 a 65 años con buen estado de salud.",
    location: "Hospital de Clínicas, CABA",
    instagram: "@cruzroja_arg",
    googleMaps: "https://maps.google.com/?q=hospital+clinicas+caba",
    phone: "11-5678-9012",
    status: "cerrado",
  },
  {
    id: "demo-18",
    title: "Caminata Nocturna Solidaria",
    organizer: "Jóvenes Solidarios",
    date: new Date("2026-10-03T20:00:00.000Z"),
    time: "20:00",
    description:
      "Caminata de 8 km por el centro de la ciudad iluminada con linternas y velas en señal de solidaridad. La inscripción incluye una remera conmemorativa y una linterna LED.",
    location: "Obelisco, CABA",
    instagram: "@jovenessolidarios",
    googleMaps: "https://maps.google.com/?q=obelisco+caba",
    status: "activo",
  },
  {
    id: "demo-19",
    title: "Rifa de Electrodomésticos",
    organizer: "Comercios Solidarios",
    date: new Date("2026-10-10T12:00:00.000Z"),
    time: "12:00",
    description:
      "Gran sorteo de electrodomésticos nuevos donados por comercios del barrio. Todo lo recaudado será para las víctimas del terremoto.",
    location: "Mercado de Abasto, CABA",
    instagram: "@comerciossolidarios",
    phone: "11-6789-0123",
    status: "pospuesto",
  },
];
